version: '3.9'
services:
  comiccalendar:
    container_name: comiccalendar
    image: comiccalendar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      containers:
        ipv4_address: 172.21.0.10
    volumes:
      - ./events.json:/code/events.json
      - ./app/static:/code/app/static
      - ./.htpasswd:/code/.htpasswd
      - ./.env:/code/.env
networks:
  containers:
    external: true