version: '3.9'
services:
  comiccalendar:
    container_name: comiccalendar
    image: comiccalendar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      containers:
        ipv4_address: 172.21.0.10
    volumes:
      - ./comiccalendar-events/events.json:/code/events.json
      - ./app/static:/code/app/static
      - ./.htpasswd:/code/.htpasswd
      - ./.env:/code/.env
    restart: unless-stopped
  notify:
    container_name: notify
    image: notify
    build:
      context: ./notify
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    networks:
      containers:
        ipv4_address: 172.21.0.11
    volumes:
      - ./comiccalendar-events/events.json:/app/events.json
      - ./notify-last-id/last_processed_id.txt:/app2/last_processed_id.txt
      - ./notify/:/app/
      - ./.env:/app/.env
    restart: unless-stopped
networks:
  containers:
    external: true
