version: '3.8'
services:
  comiccalendar:
    container_name: comiccalendar
    image: comiccalendar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      containers:
        ipv4_address: 172.21.0.10
    volumes:
      - ./events.json:/app/events.json
      - ./app/static:/app/app/static
      - ./.htpasswd:/app/.htpasswd
networks:
  containers:
    external: true