name: Lint and Commit
on: push
jobs:
  lint:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: chartboost/ruff-action@v1
      with:
        version: 0.5.7
        args: 'format --check'
        src: './app'
        changed-files: 'true'
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Auto-Fix by ruff'